name: Build for android

on: 
  workflow_dispatch:

jobs:
  build-android-armv7a:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Build android-armv7a
      run: |
        sudo dpkg --add-architecture i386
        sudo apt update
        sudo apt-get install -f -y libopenal-dev:i386 g++-multilib gcc-multilib libpng-dev:i386 libjpeg-dev:i386 libfreetype6-dev:i386 libfontconfig1-dev:i386 libcurl4-gnutls-dev:i386 libsdl2-dev:i386 zlib1g-dev:i386 libbz2-dev:i386
        wget https://dl.google.com/android/repository/android-ndk-r10e-linux-x86_64.zip -o /dev/null
        unzip -qq android-ndk-r10e-linux-x86_64.zip
        export ANDROID_NDK_HOME=$PWD/android-ndk-r10e/
        export NDK_HOME=$PWD/android-ndk-r10e/
        ./waf configure -T release --android=armeabi-v7a-hard,4.9,21 --togles --disable-warns &&
        ./waf build
        mkdir kompiled-adrod
        ./waf install --destdir=kompiled-adrod/
    - uses: actions/upload-artifact@v3
      name: Upload Artifacts
      with:
        name: kompiled-android
        path: kompiled-adrod/
